"""Advisory checker for unsafe (non-zero-downtime) DDL in Alembic revisions.

Background: ADR 056. Scans ``migrations/versions/*.py`` at the Alembic-``op``
level (AST-based, mirroring ``tools/check_examples_copyflow.py``) and reports
operations that can take a table lock or break the app/schema compatibility
window during a rolling deploy.

Only the ``upgrade()`` function body is analysed: an autogenerated revision
mirrors every ``add_column`` in ``upgrade`` with a ``drop_column`` in
``downgrade``, and flagging the rollback path would false-positive on nearly
every revision. Rollback safety is covered narratively in the playbook.

Operations against a table created in the same ``upgrade()`` are exempt (an
empty table cannot block live traffic). This covers ``op.create_table`` in both
positional and ``table_name=`` keyword form, and ``op.batch_alter_table`` blocks
whose target was created in the same revision.

Advisory-first (ADR056-G1): exit 0 by default even when findings exist. The
``--strict`` flag exits 1 for opt-in CI hardening; it is intentionally not
wired into any gate here.

The per-engine safe/unsafe rules live in
``docs/operations/rdb-migrations.md`` (single source of truth, ADR056-G2);
this checker encodes a conservative subset of them.

Usage:
    python3 tools/check_migration_safety.py [--strict] [FILE ...]

With no file arguments, scans every git-tracked ``migrations/versions/*.py``.
With arguments (pre-commit passes changed files), scans only the given files
that live under ``migrations/versions/``.
"""

from __future__ import annotations

import ast
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VERSIONS_PREFIX = "migrations/versions/"
PLAYBOOK = "docs/operations/rdb-migrations.md (## Zero-Downtime Migrations)"

SEV_UNSAFE = "unsafe"
SEV_CAUTION = "caution"

# rule_id -> (severity, why + safe alternative). Kept aligned with the
# per-engine table in the playbook (ADR056-G2).
_RULES: dict[str, tuple[str, str]] = {
    "add-not-null-no-default": (
        SEV_UNSAFE,
        "adding a NOT NULL column without a server-side default fails on "
        "existing rows (a client-side `default=` does not backfill them); "
        "add it nullable, backfill, then SET NOT NULL (validated)",
    ),
    "add-not-null-with-default": (
        SEV_CAUTION,
        "NOT NULL + server_default is metadata-only on PostgreSQL 11+ but "
        "rewrites the table on older versions or with a volatile default; "
        "prefer nullable + backfill for large tables",
    ),
    "blocking-index": (
        SEV_UNSAFE,
        "CREATE INDEX takes a write-blocking lock; use "
        "op.create_index(..., postgresql_concurrently=True) in a "
        "non-transactional revision",
    ),
    "drop-column": (
        SEV_CAUTION,
        "dropping a column breaks the old app version still serving traffic; "
        "drop only after no deployed version reads it (expand-contract)",
    ),
    "rename-column": (
        SEV_UNSAFE,
        "renaming a column breaks the app compatibility window; add the new "
        "column, dual-write, backfill, then drop the old (expand-contract)",
    ),
    "type-change": (
        SEV_UNSAFE,
        "changing a column type rewrites the table under an exclusive lock; "
        "add a new-typed column, backfill, swap, drop",
    ),
    "set-not-null": (
        SEV_CAUTION,
        "SET NOT NULL on an existing column scans the whole table; add a "
        "NOT VALID CHECK, VALIDATE it, then SET NOT NULL",
    ),
    "rename-table": (
        SEV_UNSAFE,
        "renaming a table breaks the app compatibility window; use "
        "expand-contract (new table + dual-write) instead",
    ),
    "add-constraint-blocking": (
        SEV_CAUTION,
        "adding a foreign key or check constraint validates existing rows "
        "under a lock; use ADD CONSTRAINT ... NOT VALID then "
        "VALIDATE CONSTRAINT as a separate step",
    ),
    "unique-constraint": (
        SEV_CAUTION,
        "adding a UNIQUE constraint locks the table while it builds the "
        "backing index (NOT VALID does not apply to UNIQUE); build a unique "
        "index with CREATE UNIQUE INDEX CONCURRENTLY, then attach it via "
        "ADD CONSTRAINT ... USING INDEX",
    ),
}


@dataclass(frozen=True)
class Finding:
    path: str
    line_number: int
    rule_id: str
    severity: str
    message: str

    def format(self) -> str:
        return (
            f"{self.path}:{self.line_number}: [{self.severity}] "
            f"{self.rule_id} — {self.message}"
        )


def _relative_path(path: Path, repo_root: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def _method_name(call: ast.Call) -> str | None:
    """Return the method name for ``op.<m>()`` / ``batch_op.<m>()`` calls."""
    return call.func.attr if isinstance(call.func, ast.Attribute) else None


def _callee_name(call: ast.Call) -> str | None:
    """Return the callee for both ``sa.Column(...)`` and ``Column(...)``."""
    func = call.func
    if isinstance(func, ast.Attribute):
        return func.attr
    if isinstance(func, ast.Name):
        return func.id
    return None


def _has_keyword(call: ast.Call, name: str) -> bool:
    return any(kw.arg == name for kw in call.keywords)


def _keyword_value(call: ast.Call, name: str) -> ast.expr | None:
    for kw in call.keywords:
        if kw.arg == name:
            return kw.value
    return None


def _is_false(node: ast.expr | None) -> bool:
    return isinstance(node, ast.Constant) and node.value is False


def _is_true(node: ast.expr | None) -> bool:
    return isinstance(node, ast.Constant) and node.value is True


def _is_none(node: ast.expr | None) -> bool:
    return isinstance(node, ast.Constant) and node.value is None


def _find_column_call(call: ast.Call) -> ast.Call | None:
    """Locate the ``Column(...)`` argument of an add_column call (position-free).

    ``op.add_column(table, Column(...))`` and ``batch_op.add_column(Column(...))``
    pass the column at different positions, so search all args and kwargs.
    """
    candidates: list[ast.expr] = list(call.args) + [kw.value for kw in call.keywords]
    for node in candidates:
        if isinstance(node, ast.Call) and _callee_name(node) == "Column":
            return node
    return None


def _string_arg(node: ast.expr | None) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


# Positional index of the target table name for direct op.<method> calls.
_TABLE_ARG_INDEX: dict[str, int] = {
    "add_column": 0,
    "drop_column": 0,
    "alter_column": 0,
    "create_index": 1,
    "create_unique_constraint": 1,
    "create_foreign_key": 1,
    "create_check_constraint": 1,
    "rename_table": 0,
}


def _table_name_from_call(call: ast.Call, method: str) -> str | None:
    """Table name from a direct op call's positional or table_name= argument."""
    idx = _TABLE_ARG_INDEX.get(method)
    if idx is None:
        return None
    if idx < len(call.args):
        return _string_arg(call.args[idx])
    return _string_arg(_keyword_value(call, "table_name"))


def _target_table(
    call: ast.Call, method: str, batch_tables: dict[str, str]
) -> str | None:
    """Best-effort extraction of the table a statement operates on.

    ``batch_op.<method>()`` carries no table argument — its table comes from the
    enclosing ``batch_alter_table`` context, resolved via the alias map. Falls
    back to the direct-call positional/keyword table name. Returns None when the
    name is not a string literal, in which case the caller keeps analysing.
    """
    func = call.func
    if isinstance(func, ast.Attribute) and isinstance(func.value, ast.Name):
        table = batch_tables.get(func.value.id)
        if table is not None:
            return table
    return _table_name_from_call(call, method)


def _created_tables(func: ast.FunctionDef) -> set[str]:
    """Collect table names created via op.create_table in this upgrade body.

    Covers both the positional first argument and the ``table_name=`` keyword.
    """
    created: set[str] = set()
    for node in ast.walk(func):
        if isinstance(node, ast.Call) and _method_name(node) == "create_table":
            name = _string_arg(node.args[0]) if node.args else None
            if name is None:
                name = _string_arg(_keyword_value(node, "table_name"))
            if name:
                created.add(name)
    return created


def _batch_alias_tables(func: ast.FunctionDef) -> dict[str, str]:
    """Map ``batch_op`` alias -> table for ``with op.batch_alter_table(...) as x``."""
    mapping: dict[str, str] = {}
    for node in ast.walk(func):
        if not isinstance(node, ast.With):
            continue
        for item in node.items:
            ctx = item.context_expr
            if not (
                isinstance(ctx, ast.Call) and _method_name(ctx) == "batch_alter_table"
            ):
                continue
            table = _string_arg(ctx.args[0]) if ctx.args else None
            if table is None:
                table = _string_arg(_keyword_value(ctx, "table_name"))
            alias = item.optional_vars
            if table and isinstance(alias, ast.Name):
                mapping[alias.id] = table
    return mapping


def _analyse_call(
    call: ast.Call,
    rel: str,
    created_tables: set[str],
    batch_tables: dict[str, str],
) -> list[Finding]:
    method = _method_name(call)
    if method is None:
        return []
    # A table created in this same upgrade is empty — DDL against it cannot
    # block live traffic, so its index/column/constraint ops are safe.
    table = _target_table(call, method, batch_tables)
    if table is not None and table in created_tables:
        return []
    out: list[Finding] = []

    def emit(rule_id: str) -> None:
        severity, message = _RULES[rule_id]
        out.append(Finding(rel, call.lineno, rule_id, severity, message))

    if method == "add_column":
        column = _find_column_call(call)
        if column is None or not _is_false(_keyword_value(column, "nullable")):
            return out  # nullable (or unresolved) column — safe
        # Only a real server_default backfills existing rows; a client-side
        # `default=` does not, and `server_default=None` is no default at all.
        server_default = _keyword_value(column, "server_default")
        has_server_default = server_default is not None and not _is_none(server_default)
        emit(
            "add-not-null-with-default"
            if has_server_default
            else "add-not-null-no-default"
        )
    elif method == "create_index":
        if not _is_true(_keyword_value(call, "postgresql_concurrently")):
            emit("blocking-index")
    elif method == "drop_column":
        emit("drop-column")
    elif method == "alter_column":
        if _has_keyword(call, "new_column_name"):
            emit("rename-column")
        if _has_keyword(call, "type_"):
            emit("type-change")
        if _is_false(_keyword_value(call, "nullable")):
            emit("set-not-null")
    elif method == "rename_table":
        emit("rename-table")
    elif method == "create_unique_constraint":
        emit("unique-constraint")
    elif method in ("create_foreign_key", "create_check_constraint"):
        emit("add-constraint-blocking")
    return out


def find_findings(path: Path, *, repo_root: Path = REPO_ROOT) -> list[Finding]:
    rel = _relative_path(path, repo_root)
    try:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(path))
    except (OSError, SyntaxError, ValueError) as exc:
        lineno = getattr(exc, "lineno", 0) or 0
        return [
            Finding(
                rel,
                lineno,
                "unparseable",
                SEV_CAUTION,
                f"unparseable file: {type(exc).__name__}",
            )
        ]

    findings: list[Finding] = []
    for node in ast.walk(tree):
        # Only the upgrade() path — downgrade mirrors it and would false-positive.
        if isinstance(node, ast.FunctionDef) and node.name == "upgrade":
            created = _created_tables(node)
            batch_tables = _batch_alias_tables(node)
            for sub in ast.walk(node):
                if isinstance(sub, ast.Call):
                    findings.extend(_analyse_call(sub, rel, created, batch_tables))
    findings.sort(key=lambda f: (f.line_number, f.rule_id))
    return findings


def discover_tracked_revisions(repo_root: Path = REPO_ROOT) -> list[Path]:
    result = subprocess.run(  # noqa: S603
        ["git", "ls-files", "-z", "--", VERSIONS_PREFIX],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=True,
    )
    return [
        repo_root / entry
        for entry in result.stdout.split("\0")
        if entry.endswith(".py") and "__pycache__" not in entry
    ]


def filter_to_revisions(paths: list[Path], repo_root: Path) -> list[Path]:
    kept: list[Path] = []
    for path in paths:
        rel = _relative_path(path, repo_root)
        if rel.startswith(VERSIONS_PREFIX) and rel.endswith(".py"):
            kept.append(path)
    return kept


def run(argv_paths: list[str], *, repo_root: Path = REPO_ROOT) -> int:
    strict = "--strict" in argv_paths
    file_args = [arg for arg in argv_paths if arg != "--strict"]

    if file_args:
        resolved = [
            Path(raw) if Path(raw).is_absolute() else repo_root / raw
            for raw in file_args
        ]
        candidates = filter_to_revisions(resolved, repo_root)
    else:
        candidates = discover_tracked_revisions(repo_root)

    findings: list[Finding] = []
    for path in candidates:
        findings.extend(find_findings(path, repo_root=repo_root))

    if not findings:
        print(
            f"Migration safety: 0 advisories across {len(candidates)} revision file(s)."
        )
        return 0

    # Advisory output goes to stdout (pre-commit `verbose: true` surfaces it);
    # --strict routes to stderr and returns non-zero for opt-in CI hardening.
    stream = sys.stderr if strict else sys.stdout
    unsafe = sum(1 for f in findings if f.severity == SEV_UNSAFE)
    print(
        f"Migration safety: {len(findings)} advisory finding(s) "
        f"({unsafe} unsafe, {len(findings) - unsafe} caution) across "
        f"{len({f.path for f in findings})} file(s):",
        file=stream,
    )
    for finding in findings:
        print("  " + finding.format(), file=stream)
    print(
        f"\nSee {PLAYBOOK} for safe alternatives. "
        "Advisory only — not a merge gate (ADR056-G1).",
        file=stream,
    )
    return 1 if strict else 0


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    return run(args)


if __name__ == "__main__":
    raise SystemExit(main())
